//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeAnanlysis
    {
        public int Id { get; set; }
        public int Age { get; set; }
        public bool Attrition { get; set; }
        public string BusinessTravel { get; set; }
        public int DailyRate { get; set; }
        public int DistanceFromHome { get; set; }
        public int Education { get; set; }
        public int EmployeeCount { get; set; }
        public int EmployeeNumber { get; set; }
        public int EnvironmentSatisfaction { get; set; }
        public bool Gender { get; set; }
        public int HourlyRate { get; set; }
        public int JobInvolvement { get; set; }
        public int JobLevel { get; set; }
        public int JobSatisfaction { get; set; }
        public string MaritalStatus { get; set; }
        public int MonthlyIncome { get; set; }
        public int MonthlyRate { get; set; }
        public int NumCompaniesWorked { get; set; }
        public bool Over18 { get; set; }
        public bool OverTime { get; set; }
        public int PercentSalaryHike { get; set; }
        public int PerformanceRating { get; set; }
        public int RelationshipSatisfaction { get; set; }
        public int StandardHours { get; set; }
        public int StockOptionLevel { get; set; }
        public int TotalWorkingYears { get; set; }
        public int TrainingTimesLastYear { get; set; }
        public int WorkLifeBalance { get; set; }
        public int YearsAtCompany { get; set; }
        public int YearsInCurrentRole { get; set; }
        public int YearsSinceLastPromotion { get; set; }
        public int YearsWithCurrManager { get; set; }
        public int DepartmentId { get; set; }
        public int EducationFieldId { get; set; }
        public int JobRoleId { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual EducationField EducationField { get; set; }
        public virtual JobRole JobRole { get; set; }
    }
}
